### ISSUE TITLE
Deprecation Notice: Not compatible with Composer v2.0

### ISSUE THREAD

**Issue by kierandelaney** [esendex/esendex-php-sdk#33] opened 2020-10-14 09:20 UTC
As it says on the tin. 

`Class Esendex\AutoLoader located in ./vendor/esendex/sdk/src/autoload.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0.`

**Comment by tomredhot** [comment] 2020-11-23 01:20
Same here.

**Comment by abellion** [comment] 2020-11-23 08:57
Same.

**Comment by kierandelaney** [comment] 2020-11-24 09:05
@tomredhot @abellion I raised a case with Esendex support yesterday - it's pretty apparent that they don't bother with this repository, you may need to do the same :)

**Comment by mwalton-esendex** [comment] 2020-11-25 14:47
Hello, I'm one of the Esendex platform developers. I've been looking into this issue and I'm unable to reproduce it.

First I installed Composer 2.0.7.

I created composer.json with the `esendex/sdk` requirement as documented in our README.

> `{
>         "require": {
>                 "esendex/sdk": "2.*.*"
>         }
> }`

I was then able to successfully run `php composer.phar install`.

I created a PHP script and `require __DIR__ . '/vendor/autoload.php';`.

I was then able to instantiate objects from the Esendex SDK with no issues.

I have not seen any errors or warnings from Composer.

Given this, we're going to need some more information about what kind of project setup leads to the error message you reported, and when do you see it?

**Comment by kierandelaney** [comment] 2020-11-25 14:51
Generate an optimised autoload file, which is standard practice when deploying to production environments.

`composer install --no-dev -o`

https://getcomposer.org/doc/03-cli.md#install-i

**Comment by kierandelaney** [comment] 2021-01-14 13:23
@mwalton-esendex any chance of an update?

**Comment by abellion** [comment] 2021-02-03 16:15
For those who are still waiting for Esendex to fix their legacy SDK, here are some workarounds : 

- https://jusibe.com/
- https://twilio.com/
- https://vonage.com/
- https://messagebird.com/
- https://plivo.com/
- https://46elks.com/

**Comment by tomrowsell86** [comment] 2021-02-17 15:20
This has been fixed in the latest release (3.0.0). Sorry for the delay in resolution.

**Closed by tomrowsell86** 2021-02-17 15:20 UTC
